surftest1 = geraFeatures(rgb2gray(im1),'surf');
surftest2 = geraFeatures(rgb2gray(im2),'surf');
surftest3 = geraFeatures(rgb2gray(im3),'surf');
surftest4 = geraFeatures(rgb2gray(im4),'surf');
surftest5 = geraFeatures(rgb2gray(im5),'surf');
surfVec = [size(surftest1,1)];
surfVec = [surfVec, countFeatures(surftest1,surftest2,10,size(rgb2gray(im1)))];
surfVec = [surfVec, countFeatures(surftest1,surftest3,10,size(rgb2gray(im1)))];
surfVec = [surfVec, countFeatures(surftest1,surftest4,10,size(rgb2gray(im1)))];
surfVec = [surfVec, countFeatures(surftest1,surftest5,10,size(rgb2gray(im1)))];
save();

 surftest1L = geraFeatures(rgb2gray(im1l),'surf');
 surftest2L = geraFeatures(rgb2gray(im2l),'surf');
 surftest3L = geraFeatures(rgb2gray(im3l),'surf');
 surftest4L = geraFeatures(rgb2gray(im4l),'surf');
 surftest5L = geraFeatures(rgb2gray(im5l),'surf');
surfVecL = [size(surftest1L,1)];
surfVecL = [surfVecL, countFeatures(surftest1L,surftest2L,10,size(rgb2gray(im1l)))];
surfVecL = [surfVecL, countFeatures(surftest1L,surftest3L,10,size(rgb2gray(im1l)))];
surfVecL = [surfVecL, countFeatures(surftest1L,surftest4L,10,size(rgb2gray(im1l)))];
surfVecL = [surfVecL, countFeatures(surftest1L,surftest5L,10,size(rgb2gray(im1l)))];
save();
